# 要素へのアクセス

In [1]:
import numpy as np

## 1次元配列

In [2]:
# 0~9までの要素を持つ配列生成
x = np.arange(10)

#こちらでも同じ結果
x = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### 要素へのアクセス & スライス

In [3]:
x[3] # 3

x[1:5] # array([1, 2, 3, 4])

x[3:] # array([3, 4, 5, 6, 7, 8, 9])

x[6:] # array([6, 7, 8, 9])

x[-4:] # array([6, 7, 8, 9])

array([6, 7, 8, 9])

## 多次元配列

In [4]:
# 4×5の配列生成
x = np.arange(20).reshape(4, 5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

### 要素へのアクセス & スライス

In [5]:
x[3,4] # 19

x[2, :] # array([10, 11, 12, 13, 14])

x[2, 2:] # array([12, 13, 14])

x[:, 2:]
# array([[ 2,  3,  4],
#        [ 7,  8,  9],
#        [12, 13, 14],
#        [17, 18, 19]])

x[2:, :]
# array([[10, 11, 12, 13, 14],
#        [15, 16, 17, 18, 19]])

x[1:3, 2:4]
# array([[ 7,  8],
#        [12, 13]])

array([[ 7,  8],
       [12, 13]])

## 条件からアクセス

In [6]:
# 4×5の配列生成
x = np.arange(20).reshape(4, 5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [7]:
x[0 == x%2] # 偶数の要素のみ抽出

x[x > 10] # 11以上の要素のみ抽出

array([11, 12, 13, 14, 15, 16, 17, 18, 19])