# numpyの演算

In [1]:
import numpy as np

In [2]:
A = np.arange(4).reshape(2,2)
A

array([[0, 1],
       [2, 3]])

In [3]:
B = np.arange(3,7).reshape(2,2)
B

array([[3, 4],
       [5, 6]])

# 四則演算

In [4]:
A + B

array([[3, 5],
       [7, 9]])

In [5]:
A - B

array([[-3, -3],
       [-3, -3]])

In [6]:
A * B # 要素同士の積

array([[ 0,  4],
       [10, 18]])

In [7]:
A / B # 要素同士の商

array([[0.  , 0.25],
       [0.4 , 0.5 ]])

## 行列計算

In [8]:
A@B #こっちが線形代数で出る積

array([[ 5,  6],
       [21, 26]])

In [9]:
A.dot(B) #dotを使っても同じ結果

array([[ 5,  6],
       [21, 26]])

## アインシュタインの縮約記法が使える！
個人的には，最近こちらを使っている

In [10]:
# AB
np.einsum("ij,jk->ik",A, B)

array([[ 5,  6],
       [21, 26]])

In [11]:
# BA
np.einsum("ij,jk->ki",A, B)

array([[ 5, 21],
       [ 6, 26]])

In [15]:
# ABA
np.einsum("ij,jk,kl->il", A, B, A)

array([[12, 23],
       [52, 99]])